# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:tM8JgHT6VHaq1wRhXo3ATFhj6o4oXXZUjbHnvuCiCg==,iv:GZKL6D/5EARX5ET10AQyToa2enu+EWT+tcKeC5QVIV8=,tag:AUif9yYCq+0J4igM6YqJ6w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:VAt6O5OKkdEsHTec+PikJl+7PKe0CbowczuHrKQNiyjnFMIg1g==,iv:1Im+tRfPMUTy0qsYiAbOwxxXC1OxWajtspVNyfbsgbs=,tag:i91kDDylU12M77GzQ+yZ9Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:4tIp50f2Js3/tf4IIrEIixc=,iv:lJ6w86B4YgKlS98B2Fl27tj4OJqm8Ln7+D+cPRODoss=,tag:VsSrh5MLeyuO1f+j3t8PkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdE1lOHhYei9xd2VPVjNw
            WEszdGgyTHBkcll2L2hucytYS3oxeWl2Z3dBClNwVy80TmRzaDdEaDlIN0s1T2xF
            MVBpWVA5S0JSYTNYTk5LblJuODFhZ2cKLS0tIFJ4N2hMYzdHL2I3NEl0RDN1QW02
            clhONjJWZGJLdVlSYW0yVVBYN05ZZ0EKMcso+31RtZtVX2fE04uELJRSynUwQWh5
            n1IED5hBN7TOaSX7hmbckEGN7ymdchmLVSgInbjWIxHIhc1X1EHiUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-03T17:24:23Z"
    mac: ENC[AES256_GCM,data:wnRLN3f3/545XP700Y54JRsMkK96KShxEIaqQu0AGWFZd4HOnBcph6ZuMTXpVFOYjbW5rz/4k67V8W3PZr/htdVFyXVHlB2UzOPFb81jleVdwELwBpWgQtdbWP7vv15+tmvU9IAZ0wu7MI0ptsjVn6QOWcAmyahYMIchC5v3c8g=,iv:TQAnxo7+JRXUc1X/qDfv3w5uj6Pm2SL3QQXsB2mO5xU=,tag:WhW/wATyfKPByxqwLCIepw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
