# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Bm0VZU7MytJMXkYqSsoq88EOZC3jlVD5zFxP8WInuw==,iv:FE8sPWS4usQEXssQokLwwBeqKg338+F25yjQ41TXedU=,tag:Ad1MDLeyF8nulshOvsQBdw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:j0w2uI54IykBZ4r2ci53nBpRkMkKTn8hJK/SknJjt78VZqNk6A==,iv:nHx0aBfp+71dJbD1xqyQkm+tepIzuRsz3NavvNcOHTY=,tag:33tkLJlFyUovxHCy5Zo+7A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:3+VX+nVQlnFzqAYFgPnI7x0=,iv:dbGyaWtlzGspxH3fvMyRLqhlRaaZUoOQ25VnNas0Vo4=,tag:ca+hN027qiDNfNKq6cuKSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUTF1SlBWT3poUnlFdklJ
            Y2hodWVYbFg4SWUwWlp1bVhTVHRGWmlzQms0CjVsSmdqdHRBeENtS2s1YnVqYUVp
            aWd1eHlOQjlvbWFvZnY3aGpucHRJK1EKLS0tIG5aVjJZRlFtN3ZjM0VjbEppbG80
            eUowNHYvMUFJYVlHVUZ3cFY1M25zRzAKZYanjmwT/dtrv7D8KWGxN37Ax0V50Uhw
            RIHDvz1liZldVyXOM7FIxjjnDjMjXJ30NC33Ig25tNFHSgTL31D26g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-17T18:14:24Z"
    mac: ENC[AES256_GCM,data:syVr3C39ymkGGo83VN4N4P83FBB1JQwF6E5bZ1LjqVPj4KLcrtK/SZTHIKUnch0XbwOCcMkg9qNayrO9Pq77i0w/tlnjDoMWt6yic9kA2dILFjaSXeOcDflVZ0uV9voV2IA+q03960FGZsJsYOORWaPSfZXbXmAjqDsTEHH/LN8=,iv:sXxsaTB/dPy1clzMEjco6P5IzC1ILvt5buXVwtsCXoA=,tag:O6KU7NTqiAm4AIvi4Npx+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
