# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:r2224ZZzl3flX4bZCtJ19p2og+mr1c7JmkH3cC1USQ==,iv:TOwkLGad6fi3gNSNpxpmJSAmyAUVUWIxS/rUk6vXTKA=,tag:UZOSxSIaQiQP3pW4q0yirQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:aVrPco7c9+4CdSoAVs9pntq/69VFWaxOXrtT+ZSwJF2QImiAZQ==,iv:xnVOiu//lSUEVTzTrKf/jLPE6kEFZ0OYMUhEs+eJiVw=,tag:TDEDeDAhIkr+9h2cx5UPpg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:P53pqEEtPN1c9tof124kXUs=,iv:Zn8WpH8i7mu1S1PHvX5yyaXJHIyy6iVlVAGKI98BTBQ=,tag:+1237FNahplrefTBP8MUrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZjhEYnFnUXFJaFJONm00
            OVlTc1hqdFBvUEhHRU5FTHNIUDIxb0NvRkE0CnRPNWpoMHNOT1I0SU13MVJVbDQ0
            aGg3Ung1VWFBMjZxK1pUaXpVUHZqN3cKLS0tICt5NTRFMDROYlBrSFZDb01VeE8x
            RmlGTk94WHRJUWttVGpFeklJOVByMkUKLQQ1RLXJvlM2CQtI14kPTHEZyCfBzEi/
            CUv1vWlIuGBb6psCjIMJt3yeZtyhLb6EKXSqErEmV9sv5/8Q0Gwlmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-20T23:02:13Z"
    mac: ENC[AES256_GCM,data:/8UjS0sLBxzmxku92DvfJZDRkm3HML70JTLh4AOTqS+WQ5bOUrjHr4IwW+Y8Hp0RrihULmi6NfxOdXKsYQVJ9jDCh6KtYN4vLWJaqNeLLGdBL4HzxpLMC+eO1+PaYqjydmvc6At9+3no7QjzrKtKkl9wVzWjYANW7OXieZ3aGNs=,iv:GbdlUHICN1IbjpLH4zNoUUWaVM0FmgiEf8m1E4Stxjs=,tag:fx6IgF5gyHIJyvZ02HEhAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
