# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5IyoKgOkjDbVIPwrknitq0HFxDbUFph9LXj+DBuZqA==,iv:zput0JrnM7bsBGS/NTXv6Au90tejg8IiatHepRbcr8c=,tag:jBfwz66aF4JtaQDJ0gGa3w==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:AY90+svTwfhFK5tIwe7OBwTnhif48WM7RE0AoN2LLfCOdZ6/cQ==,iv:ZEdI7exG2xoCb+42l/RwnRR1uULjN4X8WdakjvJr5KE=,tag:SVWxy6E0ZEavdmufi2f6bQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:2AAbbl2hP3QfDqbYQVsCFhI=,iv:9rWSpfdF6k8/++N1NMZ/wMqPW12YlLxFjs1MMAROBxc=,tag:Wrfo2/+PFSjtKrfW9Wuq/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S1ltZXo4MGxKOVNzVSs4
            TGtGenZQWjlQMGw4MW5sdllGV1RWMXhkcXdvCnJ5VDJZUmoxQjRaRFRtTjZPa2Na
            TFdQeXpwK3dXSEV6WWNVdGtNNHVTZkkKLS0tIDl3VFdlMTkyUTJSelZPekJWeEJR
            K2w0Nno2WDQ5Y01qeWprbzZFZmVsNncKVyFhY0kZa7niLIIe9oHbG2VOdsyb17R2
            i2GkzPKF3nPmXggx/IBXIgynM/c+i9iPcTuG8m3pHiDVIXU9A2VBew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-20T12:14:19Z"
    mac: ENC[AES256_GCM,data:3QyH2SqWVhNJ942Rdu0pSe1PwFa7kB+M1TIPSinvP4Aj7ZQM1tOsSF6L9QUzp1o67D2+XXJZavEMibxjKKdcdiTARCgf4qNrDXDV6Cf76mpfWpvwPwlUnSlWnfqkBjr7ycfWx9u8Wak7vMfNxixUJHbK68wS3tz1WrBm/O+q+qA=,iv:FIQALY9k5RiBv0glS7VWZY05rrvv5jt6TSFmnR38o9o=,tag:M62A09tAltAyx+kjJnayyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
