# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2dcpQC2iJ4SOBT6tYmuHW1AbVS6zaL1kA0jYQWWVeA==,iv:wqdye4MMil89ycDLSKZewndTW573iYN117sKWq2223A=,tag:1XvDdYT891So2D7YE0qO7A==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:/w2+JkXCPYHDeLrZSR9tMEuvjxXgtGK7zD6J2lT18CKiD+oqlw==,iv:j/peM/0eSxgLTRr5fXmTnvsKe8JU2VK1RaOc7BfilvM=,tag:CJcKbxS/Wx4xFzX+Eqtf3A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:WDvvz2XvyyWHVruaZKg/UHo=,iv:rS6Df1QDKzozs0wG70IBpl4zlz4lC7vq6s8uoWPyzsA=,tag:7dCF2UKrdbzrlwtGoiZxyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Zm01STdzRXBINE5xZFdW
            VVJYZ1pVUzBlb2ZIWDF0azJxUXVTZDJmS1ZBCm9UaEJNd1dta1FoSEw1dE9YSmRG
            cnNUZmlyRW0vaWNuSHd4SVRpeGhTc0EKLS0tIFVKZzhIT2lpRFQ2ZmllSDJYSVpW
            U3A5OURiaStCbW5XVG40RGtSNlVUT1UKV/YDokc+LYsF5uUWzMXoegEoDxi7ZKH+
            FLQiOacfdVTicTPTO6vi7ItT7hi4DNCrs0QtW8AjqvAGC9A6bfuiYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-15T20:34:20Z"
    mac: ENC[AES256_GCM,data:WJd+JRUFfPM4y+9hDxwfUep1P4w9hC5C+CPAoCeUub8JHYH1VmImPqLFOkCTrxlNip/pqBiUzDgxOReZd+mVEfpDj0LgwC1snNohXNH11f5ov8Q9e3IuNgIOVYFXm1Yl8bB1x4vhvKqQACX6zKjwWiF9knDik8AwTEZrW4QKlsQ=,iv:ISLs5InIVe7Thgxjzxwd0K5n+IHMx0Lr0VCNkVrdkos=,tag:JPhvjryKEGVua0dSAv3g1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
