---
apiVersion: v1
kind: Secret
metadata:
  name: recyclarr
  namespace: media
type: Opaque

stringData:
  recyclarr.yaml: |-
    ---
    # yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
    sonarr:
      - base_url: 'http://sonarr:80'
        api_key: '${SECRET_SONARR_API_KEY}'
        quality_definition:
          type: hybrid
        custom_formats:
          - trash_ids:
              - 949c16fe0a8147f50ba82cc2df9411c9 # Anime BD Tier 01 (Top SeaDex Muxers)
              - ed7f1e315e000aef424a58517fa48727 # Anime BD Tier 02 (SeaDex Muxers)
              - 096e406c92baa713da4a72d88030b815 # Anime BD Tier 03 (SeaDex Muxers)
              - e0014372773c8f0e1bef8824f00c7dc4 # Anime Web Tier 01 (Muxers)
              - 545a76b14ddc349b8b185a6344e28b04 # Anime BD Tier 05 (Remuxes)
              - c81bbfb47fed3d5a3ad027d077f889de # Anime BD Tier 08 (Mini Encodes)
              - 19180499de5ef2b84b6ec59aae444696 # Anime Web Tier 02 (Top FanSubs)
              - 0329044e3d9137b08502a9f84a7e58db # Anime BD Tier 07 (P2P/Scene)
              - dc262f88d74c651b12e9d90b39f6c753 # Anime Web Tier 06 (FanSubs)
              - 096e406c92baa713da4a72d88030b815 # Anime BD Tier 03 (SeaDex Muxers)
              - 949c16fe0a8147f50ba82cc2df9411c9 # Anime BD Tier 01 (Top SeaDex Muxers)
              - ed7f1e315e000aef424a58517fa48727 # Anime BD Tier 02 (SeaDex Muxers)
              - 29c2a13d091144f63307e4a8ce963a39 # Anime Web Tier 05 (FanSubs)
              - 4fd5528a3a8024e6b49f9c67053ea5f3 # Anime Web Tier 04 (Official Subs)
              - 25d2afecab632b1582eaf03b63055f72 # Anime BD Tier 06 (FanSubs)
              - c27f2ae6a4e82373b0f1da094e2489ad # Anime Web Tier 03 (Official Subs)
              - 30feba9da3030c5ed1e0f7d610bcadc4 # Anime BD Tier 04 (SeaDex Muxers)
      - base_url: 'http://sonarr:80'
        api_key: '${SECRET_SONARR_API_KEY}'
        quality_definition:
          type: series
        custom_formats:
          - trash_ids:
              - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
              - d0c516558625b04b363fa6c5c2c7cfd4 # WEB Scene
              - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
              - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
              - 89358767a60cc28783cdc3d0be9388a4 # DSNP
              - 7a235133c87f7da4c8cccceca7e3c7a6 # HBO
              - 3ac5d84fce98bab1b531393e9c82f467 # QIBI
              - f67c9ca88f463a48346062e8ad07713f # ATVP
              - 1656adc6d7bb2c8cca6acfb6592db421 # PCOK
              - c67a75ae4a1715f2bb4d492755ba4195 # PMTP
              - ae58039e1319178e6be73caab5c42166 # SHO
              - f6cce30f1733d5c8194222a7507909bb # HULU
              - c30d2958827d1867c73318a5a2957eb1 # RED
              - d660701077794679fd59e8bdf4ce3a29 # AMZN
              - 0ac24a2a68a9700bcb7eeca8e5cd644c # iT
              - d34870697c9db575f17700212167be23 # NF
              - a880d6abc21e7c16884f3ae393f84179 # HMAX
              - 36b72f59f4ea20aad9316f475f2d9fbb # DCU

    radarr:
      - base_url: 'http://radarr:80'
        api_key: '${SECRET_RADARR_API_KEY}'
        quality_definition:
          type: movie
        delete_old_custom_formats: false
        custom_formats:
          - trash_ids:
              - ed38b889b31be83fda192888e2286d83 # BR-DISK
              - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
              - 90a6f9a284dff5103f6346090e6280c8 # LQ
              - dc98083864ea246d05a42df0d05f81cc # x265 (720/1080p)
              - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
