apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  namespace: media
spec:
  schedule: "0 0 1 * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: recyclarr-sonarr
              image: ghcr.io/recyclarr/recyclarr
              command: ["recyclarr", "sync", "sonarr", "--config", "/app/sonarr.yaml"]
              volumeMounts:
                - name: sonarr-config
                  mountPath: /app/sonarr.yaml
                  subPath: sonarr.yaml
                  readOnly: true
            - name: recyclarr-radarr
              image: ghcr.io/recyclarr/recyclarr
              command: ["recyclarr", "sync", "radarr", "--config", "/app/radarr.yaml"]
              volumeMounts:
                - name: radarr-config
                  mountPath: /app/radarr.yaml
                  subPath: radarr.yaml
                  readOnly: true
          volumes:
            - name: sonarr-config
              projected:
                defaultMode: 0775
                sources:
                  - secret:
                      name: recyclarr
                      items:
                        - key: sonarr.yaml
                          path: sonarr.yaml
            - name: radarr-config
              projected:
                defaultMode: 0775
                sources:
                  - secret:
                      name: recyclarr
                      items:
                        - key: radarr.yaml
                          path: radarr.yaml
