apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
  namespace: media
spec:
  schedule: "0 0 1 * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: recyclarr-sonarr
              image: ghcr.io/recyclarr/recyclarr
              command: ["recyclarr", "sonarr", "--config", "/app/recyclarr.yaml"]
              volumeMounts:
                - name: recyclarr-config
                  mountPath: /app/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
            - name: recyclarr-radarr
              image: ghcr.io/recyclarr/recyclarr
              command: ["recyclarr", "radarr", "--config", "/app/recyclarr.yaml"]
              volumeMounts:
                - name: recyclarr-config
                  mountPath: /app/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
          volumes:
            - name: recyclarr-config
              projected:
                defaultMode: 0775
                sources:
                  - secret:
                      name: recyclarr
                      items:
                        - key: recyclarr.yaml
                          path: recyclarr.yaml
