---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - helm-release.yaml
  - secret.sops.yaml
configMapGenerator:
  - name: authelia
    files:
      - config/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
