# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:5ye2abYXzS1OxJ3XkeYstgP7xfR1IEtmzeTg8pkIyeBeC+lFwA==,iv:eUdiR9ylETJZmkSQXw+XMz3ym+fEMjq1foX9f//omT8=,tag:0cSxvh9ttKpYoYebqR9mdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL1ZFQ2dzYVZNTHMwT3A4
            blQ4ZmFHVXhuUHRDNjBSZ0VpU0wwckRUUldnCmM5MGwxWFcvYlpkdEFOdHpsVEUr
            VUpiWi94YU5pNUhCZVl1dGRUK3llVW8KLS0tIHdGald5TFo0MlBDaHA0OWJ3Rjli
            TXV5aE9MRktFd0V6anhnd2VTQzlNU0kKDD3i7esRidsa8QPvU0aLv8tCmoyi7Mjl
            Af8v01i2+R8m1NeVqxC8CyU9coD8zEJGqt9APfcUH4ly0Ublk+gVlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-03T17:24:23Z"
    mac: ENC[AES256_GCM,data:I2if2RAC4YbKbx5SOYQh3bY0vMWe78LmH5KF6+ZkXTlYSpMMKmIHCezKfqFVLUzQaHj3/zz105DzLm35t5neTfbIg1VhTo/BahHflb/hXvUy9lEwH8HVmyPkRu9hJ3B03sLaZdvBLanTuCAQzyyb72TFLVZVu6j6G1eLP8UAzLQ=,iv:izVDDI8EhzTlTQ4MlFnJoAfSU3W6yawAtdQJaG1J/u4=,tag:E6rWm8BKKlZ9klOCJ8LSbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
