# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:dwjlObKMSDIKX2Wkzv8gr6jRPIDnEJpOniOQELzx5w/gvtCjtw==,iv:yU5R8xBvxFpQ+SkJQFDHA7U4JG+IFkI6tvaK2tm/yMM=,tag:oKly5/8QosB+Kg7aehFpCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVXpUTHgxUEVzZnlkZnlm
            aVZoMWdQOXNRWnpNRzdUaXdlcVBzSm5NNXowCndvNFY2Y2F3UHRsOVRCSHRNZ3Jw
            RXB3YktyZjZYSzNMUUk1QlZJcjVzVmsKLS0tIDF5eE8vRFFXYjBHSzJXbE9TUTR0
            c1U1RXNxYjZOcDNzR2JYeWNLb2RZRnMKvFI1w4fJMes+WsplxSsNJxsyc7XfLi4X
            dSRZDWgU98qh6aLoKwqQxuVRP2Cfil93/3xlqTXXdb+VAbTdAnooMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-15T20:34:20Z"
    mac: ENC[AES256_GCM,data:lzw09AynSeh5y3q+hjhSWiW7QLe/waJ2KedSKQxRSl1CKmCKZzkXPszPcGmXj2FGYG9O1yiPGWLFjUp+lfm+Dm0+ZHSogc0Z2vaaSD5iIlPcRYzkp6EnAG7bDrLlDMk/NOqkdHVeGecKiwoBAv0DS7QMav84TJLQjbP7r8vQzk4=,iv:mMpPLIdsu4sx4meWFINDI6vFFLLnKR7QYGu9S3uhfxQ=,tag:rHQ8DEpkCWG/oqvRDioEqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
