# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:Iv0CqwZBBgnSKrslnYyylJ1eyfNNQeRgcvH5aqicMdfYTHgYGw==,iv:wR4mOAPYe3RUK7c8SacLagMKY0GU6Q2fMjSSYcGNlgg=,tag:kNwuyGoj3WVhl16juP+9Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2azRBWjJVSnN4NEp0UjVx
            V1hhZm1lWXN6OWk3QzU0dnFvR0JERjZybW1NCmlIaENmR3ZCTVhwc2JmbEI4eHZG
            bStLNEhzbHQwK3M3YXlmbjlBTXNMcW8KLS0tIGtmVXl5R1M2NzdxY2plejRTSS9q
            TGtSU3VtZHlkYXhaY2xaNkh1UjNiU3MKm5kJ9p8PmTKr88S9i56253oYv4VGAfqP
            0m2bW7PquO00OU8MqFQ8BB7yIdyo68mb+qj5fLy0Qad9Hxi/5ze/pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-30T21:26:12Z"
    mac: ENC[AES256_GCM,data:iWwnZ9oLj1UyUAYLniVAjJO+Btl0mVxoHvEVl9bni9knuWSSIYsdcyyd3Iip1xSECFfjjJNUED0KxqesH9H6/jWKLSzG48X7I53mZ+YemjMbZiwgsAbGsCTOjQd/jVmUJOrZ1Fp2iathh0lAY21vKu+HRX7QmcEilYQ8u78L1iw=,iv:8TGYeiGP+V6cWI8gToyrHxcHNoTdkoBkNsPyVNkLvg0=,tag:szN9SXfeVMcIkvJ6/sCR6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
