# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:QULL7IrVUvS0iSf4h0AnistVh3PARzRd0NM9xX+m4Q==,iv:v9jyxGhe0/yA8sl7LZuT54rWekP1WvyoFWlTRUd9Oxw=,tag:UJYXDH1vPJrIxQeR0e4x0A==,type:str]
    api-key: ENC[AES256_GCM,data:ZJuiZ53U48HG6OZ/1VickCrpuY6m1LroQZyfDOaFuCmgDRCg0g==,iv:RpCGHrW09irIwonI6ZquRd8CrWzIGd2zRScRFL5IkeU=,tag:eUSdWIRptA4K3qRYHRXdOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OVZ2Zld3K0VrRW9hS3Fw
            NTE4aEhac2hWLzVjRXJaZGxkdjQ5NmRDNkNBCkhnbVBwSTZSM295a2lXMkcyRVFy
            Tkt6UmZSem5TR1Byd040VWNZQmgrWk0KLS0tIFFkdHF1RnlrV0lrOUhkRlFUZ3NM
            aFY5SHRKTU5ZZ2Z1K05la1FzLzgySncKWGFuDDE1E6D7a+bEPoC+RSM2z22UYlhM
            2ifCg+gruB5Y8gNQ+Bf7WKDqSl7pp1lZRHWG9CfnSfm5G33Nha+gIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-16T12:09:06Z"
    mac: ENC[AES256_GCM,data:OFiPEpz4zeDH1dqF0yMT+t2e13ViKYe8E68QD2XTVNNMGkK6s1ocW2YTR/1zUMysU4D0+1iJH4dexe8MUsrFUtduLTU1dm05BJaMF8BdGef+39nGJ+zonBJwhVx+UG2tciauHVSvnl9ak1pySrny2JPjT+PnoSz4STl7HHMjuI8=,iv:D6aOvav45g3gtY/eJxtJxbKxfuRIfDSUYv552OPdPxo=,tag:coIazF2+8pTnNvDf9s+vUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
