# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:taKe/IyKV6/jbbnt+8l5x7Zu6f13McZEHd4jio5UiA==,iv:0/fYA3oZO+xCx4vVzj9H7ZJE0XK+QA7ZzZBXcfb2sVs=,tag:F9z5zoFALbj8EaDLSSFN6A==,type:str]
    api-key: ENC[AES256_GCM,data:viw9hwc9GKyJALAo5ZSubRdc1qSM1HgzzGbaO4E/RWkOrvquvg==,iv:uc0PtJcNH9KGVifykVdWkUnji5pV++nCoxC4MPsZ+bg=,tag:Sm0jwRE4ScyQUxB8utepmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OTNHVFZDdGI3N1hJQTVH
            WUZuTmFFcUFrRDhwVmNqUXhMekdUYjJhbTFnCklqYUE3bGxaVUVUbi9PU2RnR0dn
            K2tPMXhzdnRMTXE3bHRqR0liVHROUUUKLS0tIFdJUWkwb3BCa0hKSzZvbWpETzJh
            RkdYQ3o3cGtDK0YrdXVJY3QyTWRvWVUKiYOmO+3UK2gue5PvM7MISCI7z0y5IGcO
            kgRRnU+ZAljmJ6A+cJfryM4ApsEa5M0FJYbb5jI+1HbUa0AvgZY61w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-03T17:24:24Z"
    mac: ENC[AES256_GCM,data:o/4R/ss5logR/SqIstOfWnreaPlQtD5Uq67HhRuFykMP8LR7oVQ7FBA/WHKdXgAvtPGu83CGUabX40mt2jdTxuOM/xmOITc6Zzy/70aYDBpBlJx5jTBREtHdrN4zPOQo2K18xyhDx/dzDJngk+vsixcwtGBafHi+erWLI3Ybeb8=,iv:cM8grk6vowyzVUnT6phksCE5XNyK8mgWKIjghgGyRt0=,tag:+48+EJ1xMXzyurE4AK5FUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
