# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:uoQECLAS+/um7omcHcHg2TT5vcp+WypAmKJlZ141Vw==,iv:AKOqwcTNIaweM6LIHRJf3kiyAqEVPK2sEUOqQPZzR9M=,tag:xEeLWZKcH3YR5zrItWdptQ==,type:str]
    api-key: ENC[AES256_GCM,data:Kt0TL/50lR1dAUbFkMjW+/O8Ea3HMxhtN5i5AY8SlRp7G8Vmdg==,iv:B16JCjfjKHRQAuXVu8ooCR/YFIBUaQLx3MB3OyMUjYg=,tag:eXgo+gHlIuchNmbEEFQiSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VFRZbGNHN3BOdzhKc1F6
            ZUV4MjFCcEJEZVd5OTlRQzgvSFFOUXJoSWhNCmFxU3Z4ckdudG1wVHFnckU5K0hS
            S2dqdjcrZXpwbTh4djlsbmlpTmxrZ00KLS0tIFVST012cEptaVhkWTRFTmxyQXBw
            VUtQbWJHNjRTZWN1ckhyOXJOOFBpelUKH773UQSVt/c0jGLF2JszJ8G9qU6wFdcE
            3BCRxYtqtkwUybGxnfLci5ME2Zpym+aMvHq+yVlPPENRl9MZbohIjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-20T13:51:37Z"
    mac: ENC[AES256_GCM,data:uJZblHerHVP/01Mgqd0u0Xnk9X186SSrovk/Ccwh3yPx2RhViMkgiU53D5Grz+pGG4jW5FW3LXf6QrzGfdcjwTUrbMuDpzKpvZzWtvVXBEi9iBqwrO8r0uEeO4XxA54ocdBeZFVSeZMYY3p/Qr/R4vPXvi0ipf7fhbqk6WuG99U=,iv:GhXrIqino03YI4tfoa5KIQYPEIE+nGrn91HgNauv9mY=,tag:5yJdK0a1R9fX51UrwdBKgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
