# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:Rg34EjgAjGPwASBunXwH8+Jl0db05DCy7h29oBaokA==,iv:e1CBSZE28cQe3BA56qzIb+GR48qXcdStmgPApu+M8fE=,tag:eCfUSdfz/45zypwhtYqd8A==,type:str]
    api-key: ENC[AES256_GCM,data:nYTjVOevzxQ8+Ox/xbXCzU/j8/wLR0e0UnydSGnnR9khNfe7bQ==,iv:pk/QvEMByLUe7eJwKVR2wTa3CulVcUpRc7tWdXDPJFo=,tag:2ZTES8vjNrlaFiFCaZoPfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUHhzd0ZKZUltNG16dW9t
            QzE3L2s0MVY4djRCeEhkbWRxVTk3bVNEVlFBCm1BM3RNL3lFQm1QNzlmeTNXdEVU
            UWF3NlVLdW1PS1VneitOV2ROSStBNWcKLS0tIG5PdU0wTGxTRWVUd01rQXZzL0tI
            c2kyVXA2VDVxWW9RUXF2b1VsTENoOFEKCDwRYhfaRgxbCthU/gnYirg3NjHIj6Vh
            LYNJd9J1++9oGsfe9udCW7ntt/hjffuFCTEUMMNWE+UTzyxboUnV4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-14T16:14:37Z"
    mac: ENC[AES256_GCM,data:DeA1+fZLbTm8053Nlac7ZsBv39cvX7OGAcF4iiSZOAyXDv6GtnlU9KpmwsBqeURFYj+HQ51XBbCjQH+k9HUbM0Ec31Fzs+LBzy+vDlVQlhJKFzA5uVjb4c2EJhzAIvRGSaInDysa6z7UoB24/O+RrMSnBdZx0xr86er1l3q/jL0=,iv:9tZrg5MEI0xFXaL7gGN1qzepBtCaHVySuyHK71z0F6g=,tag:wKvR5ba5GgpKgI62/zeNfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
