# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:lnDYl6oopt2fZZxu34Qda/oCaB+G9Ecrpi2wIBWuxQ==,iv:BGbXmazHVZID4rYU1Hrgb8DrEk8p/714t5VQRULHGz4=,tag:lok2mDShNgSb+esuOpzdoA==,type:str]
    api-key: ENC[AES256_GCM,data:Fh7flVoXks6hmExSz9ZoOJsr7TtHtqtvD+TG/iRjWSgdfsJyPw==,iv:IAvgwv6t1FWem3A3BabnjUyyOasP0uzLnr4Ax1UNuvc=,tag:ZhkoLM9y8aEsx/6O4lmt3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZFFacVZtQU12L0NoR0ZL
            ZVRGWlJwWTRUVTVKSlpwSWlXbnZQQ3VSdERNClYzcElvT0hhcVdiUThiM2ZIeDQx
            YU1veEhaMzJHUHVzZmQ4SkVELzVscmsKLS0tIEpGZVpaLzkrQTV1aDBIUXl6YTZP
            SzVvbmJWMmZwNldjSHpZbmtDZC9CQjgKf7q47/ioKsGpxURy8D9/rHvOPnxJIAwn
            p2MSBs1VWPgf9NkpevwcLlxiT3jTH7+s5ltbLvooLKSBlmXDHdVZYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-17T18:14:24Z"
    mac: ENC[AES256_GCM,data:8V1fWXPygDc06Hhlky/RlAsK8fOFnZruf+ekGvmv9L9CHfy0r4q/axu+GnJK+ZTHY49YsOZLrqzKS9DQch9dm65toOFzsSwFIMJAq7aDmhaueq/V5NaBgFHgzqy5w0do0W/4VMjvcl7azBFLj8GJEP8GWACT067i15pr/9ttXbw=,iv:xqhD5fXhzpCnIaj+5AVMRQ+t8vEcGuAmeHr5xOgE2Go=,tag:8eYZdNg7pnUAfK9G8L4+fQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
