# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:qqPtt2GteGgvVwRv,iv:h1wK3kyeOvdv+uSrN8UTatIiC84BIk5Jw21QDhk8A5o=,tag:LvhEaV/qXjpPvTD3N8wi9w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Qy+CcNp9/Ns8+9iGDIRnqSICX5Y728rSHsbcGe19mA==,iv:gF0v4kIY3cPe/zk7gPM28vUtxbEulsUhxA2VX8Z2SX8=,tag:VM1UjxMtp7j6M2hcQnDhOQ==,type:str]
    SECRET_NAS_ADDR: ENC[AES256_GCM,data:XtFpCbScGCac/444,iv:kVBvXp9Kpr4M46gWyUyyz9gD43MS+ujB419nnXECehs=,tag:HFfkY8/YmlpXOKkYan0Lfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcTR2dlp2QWhHWDd1eEli
            VFpyV1dWNEFBKzdaZTE4RXNGVG5ZQ2E0UlU0CkVtWHJPbkxSa1YrTURiR2xVOGFB
            SXF0aUZRVGszdHUrU1hxVDlIaFBMSkkKLS0tIEdaaTBuOUZ5Ui9IRGF5MGJROEZl
            dGVJSlNmZ05veE9pd2wvMzUyTGV0WGcKCl0WOEd4d1aO1zPmjUc0BBCIZk+PYS/V
            298BwcUBLbTaHVgsSiQXf7Zc4JNYlAI5WESB9hND243nGR71avtyaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-17T18:14:24Z"
    mac: ENC[AES256_GCM,data:mIPjldOyFPM1cAD9rPB/D7AH7bmgn6YBTayz9E83gJxbInz/HSqL6q+6pZoCa/7sn8KQXvZUD9777FgNFCHYYrCbpbgpHMCM+eZisEn4S9AYoPhAQ7CooNVCQSr1H2UukWvz2Cll/HY6WQ7XoqOnUmntGJdoYovUMjPkUe429zc=,iv:mi9bPVHAcZrpBImUhCeeDvSSSTkQkOZUpNd0/trqnHs=,tag:mjHAVL9xOcWBtCPfORPW8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
