# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Ypv3XuYZGvf56EL2,iv:0sUhAP4zQ2IC45BSSDgpCbWy/Taa8DWWDmOqMNe4m9w=,tag:F77L+s5JViwXUHHiXpHgiw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:r9LpTcPKJx3t9QaOXXObw5EGoJ+A0coXq9G0NmyiFA==,iv:Tv71D7GMWkvv45k8j7/WJfF+drI0wUtq55CjsEfCj8U=,tag:B+b2pk/dpFhpYTqqxnhUZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQm9MbStrcTNPOU9MSVo5
            R0dXa0UvNFZZZTNHNWNHdzdRT3ZZbkUyWlZzCnlwRTBoUGUxeFBHenVxZ1NISG13
            REhaMm54WVlQWTVxWTkxblRtOEV1b2cKLS0tIGg1R09TSmtudHEyL2dMZHo0OG1z
            aGUzQWJSaXZ4US9VQ2luejNUVlZjeHcKTod7EUDAMnggJRZET/ylLpPBeyg0olZ/
            rkyGmZLDFK9NHcwQVwbjPXueSN3viKcxNNK6oZuSajECxCxgertaQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-12T20:39:43Z"
    mac: ENC[AES256_GCM,data:7at9bwSpUaImNQisrqaVN8s/PKEWbTUoDHzi3zcYbuShb4Lqmu326U8ITMu2XcwHqa4D1ZGDg8jO+xITnqfCrPafvKNO+sjDi+zh0gKw9xIyIbxvRIr4nGC+4QMnVgXkMa+z0Y1oQ1NfFF3zftHSY3tkzCix8fQB3t60eo5+E/8=,iv:3O38z1eudsV0/6kcQyDfR2CeE+NLHgHxx+BWWgh6MT8=,tag:b6WH0B9gR3HxLrU5E22YkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
