---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pterodactyl
  namespace: games
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
    external-dns/is-public: "true"
    hajimari.io/enable: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: pterodactyl.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
        pathType: Prefix
        backend:
          service:
            name: pterodactyl
            port:
              number: 80
