---
session:
  redis:
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.default.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.default.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.default.svc.cluster.local
          port: 26379
