kind: Secret
ansible_user: ENC[AES256_GCM,data:YGel7IU=,iv:mv1CgBua2qas+5p2JfMqwaMhm050geRbQF4AahqzmH8=,tag:S2VQmmD1cmDebYdNQLfKog==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:p5D97Ed45FkmfET4,iv:JtDt+9CxTD2dpi34s395kIr0IiM8VdOnGRPq3639a7k=,tag:YSIxfCzsQTiknX3MCtLV9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNCtKdTNGUUFERk5uU2t6
            eVFKT0tjclNVTzFTeU1BNjlNRVQwMFM4VkdRCkpVWFNQMkJjNFo1NEhrM0V0UkRx
            N0g2YThzVmk2MWtPMVNRcVVpb3BkNW8KLS0tIHZ4SnAxcmtaZjJSTzFPcGdTU0ph
            R25kN1cvL3dveUJGWVQ1cTFaZnJlLzgKs4arifTY6uBFPkxIsCiYho9kloWsKcss
            OnLIbBTvkIbVpS8Z28C0AvsuEiVgfVCH9jAJQcoiUNOuOd4b5nAO8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-03T19:07:47Z"
    mac: ENC[AES256_GCM,data:sD+KIzEIGb6zhJqeiOwcmcBcZ47GcRfWw2attUS6XDiY3iUu4nnEhZq7NrZdZcujR9KUWfc4AAXZEqSsOOjgznEPQSR5bQLYmReDs2V1lIJhk86V8de6IJYp5bm6idl9Q4Q9ZqQ4OEU9BtpGeadBrWHxvnsjyqOnNme3umlrSQc=,iv:YMJlKT1Va2Ao78xX/tdCLflJeA+fyTWf9dkuhTBSkP4=,tag:yE4UDvkMoqzRX69BIHoaoQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
