kind: Secret
ansible_user: ENC[AES256_GCM,data:f4WcWig=,iv:/R1bkNtMLc6aYrUfy4sxLjohIPYnivo7lQxo1lry48M=,tag:i2Yuk/s2P+ctugOTswt7mQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:bt/QnBTMu76bPa+h,iv:kV/lRKTf2M7j0bcvrNDIz1If3/muP7TyEZwG3+LeIus=,tag:W11Nj1QvH/sWD/CwUtc3eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNVlZUkhQRk5ZbGJUNWdG
            VnhJV3hYMlB0NXhiMDBmdldWQmErTWExbHo0CkJmaGRseHpudWVxMkptamZiVE9p
            QTJlcGZodS9tNlFyOFZuWDlPQVM5UW8KLS0tIEdlRWU5bUUvKzY3cDYwVHR1Smth
            WUp4NGhnbHJYR3dROWdScFlMR1R1dzgKjhcWlnyMvLYXDhZJ8u83mDKHKGD0NQtM
            iSLNT0Wnck4hXciarHDoZ/ev4mzslgQfQvBiGs3o8LSoqNutmhGCHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-02T14:43:46Z"
    mac: ENC[AES256_GCM,data:a/ZBqzH0Ylf5dGvyq2XPMHCWOrYuQpwMgl4ZrSs/lrB1gJ04UiDATeoCB1oBsxT7GEuHJhxLk3gFuXKchozYU5eG2X0f0p/+KPcG7PNvBtEOFuu7BRpq3TryvGL7JqLa2wlcbAjdmAbAuKlBKMi3ntJeJ6x2ut/QtIbdsXkfEpE=,iv:/LIU9MWQUuzwgANVkZvdqZv2I2vgBIvXq3YZdWoFsaY=,tag:takv4q8h7nLp3beo+y6GKw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
