kind: Secret
ansible_user: ENC[AES256_GCM,data:Yyq18Ok=,iv:keg3n7hvmMWk5NurKsXCQZQexdBYyk4i8dvoZEOS47E=,tag:lyakeIFaUR/eRJ1cvzeHFw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:OwYMky8QqwsY2mYQ,iv:8a3fS7cmi+TRlRR+1uhXboJK/TJhQJKSXeHnBM2HWlg=,tag:4euzpDr3yD+rm2CgNHXdiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNG9NRi9ERzg2T2IzQnY2
            M2ptSXExdE9LdjI2cC9HU0VkTUVCRGhKUEdBCmRCZEJWODBUL2VGbFh2b0FwdG1h
            emhZSWpad3J2UlJuQVFDbVBaOTJvM1EKLS0tIFl3Ly80djN0dHlCUTRjRUxBcnEv
            c3M2MkhHOWVUU0Q5akJkbStTME82NkEKuvTepQyiJMOfytwqOxLKi1r2dQ+a/2Q1
            ZAAgiEsAcc7SQ4Grux4QxyDgQioUYiQtUxXrwIKjrExIdZWEeTqung==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-15T20:34:20Z"
    mac: ENC[AES256_GCM,data:YYwk6y7gIq5SM4bBiIejnehyvxFtM7kdooABD58GEjQc6ZoxEcemWW02ZXIOsIZA2ZpKahVGiO1s5qv0NT4py9y5mY21S/YccUKS83Narky44qxjmqSMecgq+ddz4lO4XXMK7DGJO/ZlljkP1qlI/SfTUoRAaq8ZOG62ig1/00k=,iv:T20E+N3Ejr4zOjshx3p87EcTG0Fy6TQKoeeXw2VJkKg=,tag:0siQWYZYEX4TaMYqKJcNLw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
