kind: Secret
ansible_user: ENC[AES256_GCM,data:EkU7Hvs=,iv:CG709wlYPADWZa574so1eWweAXZbgV8ea+VtK7r+Ask=,tag:rDMTczXO/MznSVh4ew5mqw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:J3xZYKUIg3UZUxJq,iv:1DFFchM37vGOolQQa0E1WLXT47Qf0pkrh28HzJsaMGM=,tag:EsKRJVhm8pYMQz4/JAcnQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdVhqdFZTR2JzdXUrNWEz
            M1JXU1ZzRTRBWG1NZ1V4SFIyS1VjMUJ0TWowCk5aTGJONXMrcHg5TDZ6WEQ1SHNN
            SU5xeG90ampjSVB3R1Vpd1JNSmU0RHcKLS0tIHY3cVY4OUplakR3WDQvVFkvS3gy
            d0duZk5kc0luL09jUFJMQXFXYTdWbHMKeDluHfzBHjYwlRNjtcxhbMjkbt9tDUe0
            JQlyP8zdTP9x2OhygrmRKgc6169u7PoGfCidPPMgaTy+muSQHo4Zvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-20T23:02:13Z"
    mac: ENC[AES256_GCM,data:pZZY4pou6doZBA5upLt8ifwz3pQs+2vORyrUgJMSjOjF7AYp9HsPye6PUc75DYD702HQMbBJfBg8D8zhEWUv7QWuRV5iPEKEsTzpYiszVmsfj1kPDUa4+EqfomuYMshcl5jG/et0suIekAg2VGsuye0ur4VtLBkEbvOpGpH1Dqw=,iv:wOr70ZgtI9dgVmoDBGoHio4YKkGMpI3ByJp1ER1lKHg=,tag:C5p/S/psFyUe1Q9HbRNEUg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
