---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    snapshot.home.arpa/enabled: "true"
  name: qbittorrent-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-jiva-csi-default
