---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    backupStorageLocation:
      - name: default
        default: true
        provider: aws
        bucket: velero
        accessMode: ReadWrite
        credential:
          name: velero-secret
          key: minio
        config:
          region: "us-east-1"
          s3ForcePathStyle: true
          s3Url: "http://${SECRET_NAS_ADDR}:9000"
          publicUrl: "http://${SECRET_NAS_ADDR}:9000"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
    schedules:
      daily-backup:
        schedule: "0 6 * * *"
        template:
          storageLocation: default
          ttl: "120h"
