---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: velero
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: velero
    configuration:
      extraEnvVars:
        TZ: "${TIMEZONE}"
      backupStorageLocation:
        - name: default
          default: true
          bucket: "velero"
          provider: aws
          credential:
            name: velero-secret
            key: minio
          config:
            region: "us-east-1"
            s3ForcePathStyle: true
            s3Url: "http://${SECRET_NAS_ADDR}:9000"
            publicUrl: "http://${SECRET_NAS_ADDR}:9000"
      resticTimeout: 6h
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.7.0@sha256:91b0be561037f3b6420ace15536996afed5bd0fba537f7ab8e171587977cdc83
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    snapshotsEnabled: true
    deployNodeAgent: true
    upgradeCRDs: true
    nodeAgent:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi
          cpu: null
    schedules:
      daily-backup:
        schedule: "0 6 * * *"
        template:
          ttl: "720h"
          storageLocation: default
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
