# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ${BOOTSTRAP_CLOUDFLARE_DOMAIN}
  SECRET_CLOUDFLARE_EMAIL: ${BOOTSTRAP_CLOUDFLARE_EMAIL}
  SECRET_NAS_ADDR: ${BOOTSTRAP_NAS_ADDR}
  SECRET_RADARR_API_KEY: ${BOOTSTRAP_RADARR_API_KEY}
  SECRET_SONARR_API_KEY: ${BOOTSTRAP_SONARR_API_KEY}
  SECRET_OAUTH2_PROXY_COOKIE_SECRET: ${BOOTSTRAP_OAUTH2_PROXY_COOKIE_SECRET}
  SECRET_OAUTH2_PROXY_GOOGLE_CLIENT_ID: ${BOOTSTRAP_OAUTH2_PROXY_GOOGLE_CLIENT_ID}
  SECRET_OAUTH2_PROXY_GOOGLE_CLIENT_SECRET: ${BOOTSTRAP_OAUTH2_PROXY_GOOGLE_CLIENT_SECRET}
