---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: ${BOOTSTRAP_TIMEZONE}
  METALLB_LB_RANGE: ${BOOTSTRAP_METALLB_LB_RANGE}
  METALLB_K8S_GATEWAY_ADDR: ${BOOTSTRAP_METALLB_K8S_GATEWAY_ADDR}
  METALLB_INGRESS_ADDR: ${BOOTSTRAP_METALLB_INGRESS_ADDR}
  METALLB_PLEX_ADDR: ${BOOTSTRAP_METALLB_PLEX_ADDR}
  METALLB_QBITTORRENT_ADDR: ${BOOTSTRAP_METALLB_QBITTORRENT_ADDR}
  NAS_BASE_URL: ${BOOTSTRAP_NAS_BASE_URL}
