---
apiVersion: v1
kind: Secret
metadata:
  name: velero-secret
  namespace: storage
stringData:
  minio: |
    [default]
    aws_access_key_id = ${BOOTSTRAP_S3_CLIENT_ID}
    aws_secret_access_key = ${BOOTSTRAP_S3_CLIENT_SECRET}
