---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-jiva-csi-default
  resources:
    requests:
      storage: 10Gi
