apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-superuser
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:/5dcCIk=,iv:JbmuDSa1yy/DIoC2BGkNN/dwdPOE6EloBBB7qyL4wHk=,tag:MM5oYUISZY4YTsAamMrefw==,type:str]
    password: ENC[AES256_GCM,data:4CAYSXOk//yFfCGD,iv:+8RXv7aM2PKDRfhV5aJjmuH2ZXRgwWzG+Cj7i2OssHk=,tag:JFQ6zjUKqrBmih3cwGoJwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXamdmQmRPSk1lVWxCMW9Y
            QVVZR1FrWDV4NHZRc1l3Y1VVYVdhc29YTG1NCnd3cnR6RklLWEw2OGtVb2pBQ1FT
            emlZVjE5TGtkVEdKRnJoUGpjeWpUK28KLS0tIGFheERMWnNsQmxrTW1tMExROWQ3
            aFE2eGMrbGR4eXlWTGlub2Njbm92eWcKTi7ohMb6M1LzCrgHqoiPOlLq4eVVaVH7
            QbQWV+00RURTDeMGEOH+Hh5KIn3skrp2IOely8lnZQb3anMgliWDrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-19T21:15:51Z"
    mac: ENC[AES256_GCM,data:0N/K2flJEx5l+1dIcPznf9Uw7mcFuydKJaaJGU+cqSwvHT1ht0t7b9g6lbprfM3DyFX8FVhZfzcY+IQB9KIJhMnKYeXhYucPuj0HXTT8bgWcnNQXiJViKnUUj1l7Jczb7lNVnZLeglo0IqSCoEr3lgjOQIuB25rgQnppAceRpnU=,iv:vbYkYy7V7NIwzxzxHZFtKhbuMHSeEMndI2fgRWpqxP4=,tag:Vniz+0mUZgVIT/NkCeheMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
